package com.shinstrument.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shinstrument.Bean.DataFlow.ReUploadBean;

import com.shinstrument.greendao.ReUploadBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig reUploadBeanDaoConfig;

    private final ReUploadBeanDao reUploadBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        reUploadBeanDaoConfig = daoConfigMap.get(ReUploadBeanDao.class).clone();
        reUploadBeanDaoConfig.initIdentityScope(type);

        reUploadBeanDao = new ReUploadBeanDao(reUploadBeanDaoConfig, this);

        registerDao(ReUploadBean.class, reUploadBeanDao);
    }
    
    public void clear() {
        reUploadBeanDaoConfig.clearIdentityScope();
    }

    public ReUploadBeanDao getReUploadBeanDao() {
        return reUploadBeanDao;
    }

}
